id = 0

[router]
dir = "/tmp/rumqttd"
max_connections = 1000
max_outgoing_packet_count = 200
max_segment_size = 10485760
max_segment_count = 10

[v4.1]
name = "v4-1"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 1

[v4.1.connections]
connection_timeout_ms = 60000
max_payload_size = 20480
max_inflight_count = 100

[ws.1]
name = "browser-interface"
listen = "0.0.0.0:8083"
next_connection_delay_ms = 1

[ws.1.connections]
connection_timeout_ms = 60000
max_client_id_len = 256
max_payload_size = 20480
max_inflight_count = 500